# permissions for end users to view usedapiversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usedapiversions-viewer-role
rules:
- apiGroups:
  - api-version.wayfair.com
  resources:
  - usedapiversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api-version.wayfair.com
  resources:
  - usedapiversions/status
  verbs:
  - get
